name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file backend/Dockerfile --tag backend:northamerica-northeast1-docker.pkg.dev/language-app-323017/repo-1/backend \ docker build . --file frontend/google_patents/Dockerfile --tag frontend:northamerica-northeast1-docker.pkg.dev/language-app-323017/repo-1/frontend \ docker push northamerica-northeast1-docker.pkg.dev/language-app-323017/repo-1/backend \ docker push northamerica-northeast1-docker.pkg.dev/language-app-323017/repo-1/frontend
