name: Build app and create a release in Cloud Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: language-app-323017
  REGION: northamerica-northeast1
  GAR_LOCATION: northamerica-northeast1-docker.pkg.dev/language-app-323017/repo-1/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

      - name: Build backend image
        run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}backend
        working-directory: ./backend

      - name: Build frontend image
        run: docker build . --file ./Dockerfile --tag ${{ env.GAR_LOCATION }}frontend
        working-directory: ./frontend/google_patents

      - name: Push backend image
        run: docker push ${{ env.GAR_LOCATION }}backend

      - name: Push frontend image
        run: docker push ${{ env.GAR_LOCATION }}frontend

      - id: "compute-ssh"
        uses: "google-github-actions/ssh-compute@v0"
        with:
          instance_name: "instance-1"
          zone: "us-central1-c"
          ssh_private_key: "${{ secrets.GCP_SSH_PRIVATE_KEY }}"
          command: "echo Hello world"

      - id: "test"
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
