name: Build app and create a release in Cloud Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: language-app-323017
  REGION: northamerica-northeast1
  GAR_LOCATION: northamerica-northeast1-docker.pkg.dev/language-app-323017/repo-1/

jobs:
  build-push-artifact:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: gcloud Setup
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }} --quiet

      - name: Build backend image
        run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}backend
        working-directory: ./backend

      - name: Build frontend image
        run: docker build . --file ./Dockerfile --tag ${{ env.GAR_LOCATION }}frontend
        working-directory: ./frontend/google_patents

      - name: Push backend image
        run: docker push ${{ env.GAR_LOCATION }}backend

      - name: Push frontend image
        run: docker push ${{ env.GAR_LOCATION }}frontend
